### ISSUE TITLE
Broken link for "The syntax highlighting uses F# Formatting"

### ISSUE THREAD

**Issue by danysdragons** [tpetricek/FsSnip.Website#102]
The broken link is at the bottom right, "The syntax highlighting uses [F# Formatting](http://tpetricek.github.io/FSharp.Formatting/)"

It may be intended to point to https://fsprojects.github.io/FSharp.Formatting/ now

**Comment by anthonyflores-github** [comment]
Hello, I can do it if you want. This is one of my first contributions.
