### ISSUE TITLE
Some fields aren't showing up when creating a new public snippet with Firefox

### ISSUE THREAD

**Issue by natalie-o-perret** [tpetricek/FsSnip.Website#113]
When someone wants to insert a new public snippet the fields below aren't showing upon unchecking the "Hidden" box:
- Description
- Tags
- Author
- Links

Very likely the case that the lib used for binding isn't Firefox-friendly (or the other way around, depending on your pov), in particular, unchecking the box doesn't change the `style="display:none;"`  html attribute value for resp.:

https://github.com/fssnippets/fssnip-website/blob/9982556e94bfb1f5b3429d942ea7c60a4d333dbb/templates/insert.html#L44-L56

https://github.com/fssnippets/fssnip-website/blob/9982556e94bfb1f5b3429d942ea7c60a4d333dbb/templates/insert.html#L65-L86

Firefox
![image](https://user-images.githubusercontent.com/11332444/197687434-98e71b72-d46e-4a3b-814f-9237a481373b.png)

Edge / Chrome-based browsers
![image](https://user-images.githubusercontent.com/11332444/197687612-15a30b46-18d1-4979-85c2-0f25d0bc2d91.png)

**Comment by tpetricek** [comment]
Thanks for reporting this - that's odd! I'm using Firefox (105.0.3 (64-bit)) and the page is working - do you have any special settings that may be blocking this? (I guess more things would break with fully disabled JS, but perhaps there is some other option?)

**Comment by natalie-o-perret** [comment]
> 

good question lemme share plugins + firefox version

![image](https://user-images.githubusercontent.com/11332444/198122079-c7cf052b-8519-4d53-8b8c-1861b480a8db.png)

okay then again another update

![image](https://user-images.githubusercontent.com/11332444/198122334-25cdfb15-4ca6-4e74-940b-73269a84f2a9.png)

up-to-date but still, the fields relevant to public posting aren't showing up (curr ver: 106.0.2 (64-bit)), it seems that according to the js browser console:
![image](https://user-images.githubusercontent.com/11332444/198122534-1f7a2093-e661-469a-a835-edcf3c2dbe29.png)

plugins

![image](https://user-images.githubusercontent.com/11332444/198123055-af661a59-cef7-47db-b852-997da714908e.png)

extensions

![image](https://user-images.githubusercontent.com/11332444/198123123-30100c18-a309-4479-a607-863d1fbcb422.png)

**Comment by natalie-o-perret** [comment]
Alright it seems that I had something in cache (private nav / incognito shows that everything works just fine), could it be that there was a previous version with that issue (that would explain why my browser kept sticking to it)?

A cleanup it's all fine now.

Sorry for the noise!
![image](https://user-images.githubusercontent.com/11332444/198123823-a2e58060-cb01-4b8d-8af6-b497b9feb31f.png)

**Comment by tpetricek** [comment]
Thanks for investigating this - I have no clue what's going on, but I'm glad it's sorted out!
