### ISSUE TITLE
Insert new version is not implemented

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#14]
Related to #7 - we also need to implement insert snippet!

**Comment by treefrog00** [comment]
The current design of index.json is that each snippet's index object includes the field "number of versions". This suggests that there should only be one entry in the index for each id. However, each index object also includes author, description, etc, and I'm not quite sure what you would like to happen if a new version changes these fields?

**Comment by tpetricek** [comment]
- I opened a new issue #37 for this - for now, we can just keep the current behavior.
- So, the remaining work is to add the password support, which is now tracked in #38.

Thanks a lot @jamesjrg for solving this one!
