### ISSUE TITLE
Add JSON API

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#15]
The current web site has minimal API that is used by a few services (Try F# and Fun 3D). This needs to be added too. 

Here are the things we need:
- http://api.fssnip.net/1/snippet/11
- http://api.fssnip.net/1/snippet?all=true
- http://api.fssnip.net/1/snippet (PUT) - see for example the [Fun3D usage](https://github.com/tpetricek/Fun3D/blob/master/app.fsx#L261) of this

**Comment by mydogisbox** [comment]
So you're looking for:

http://api.fssnip.net/1/snippet/{id}
Get

``` javascript
{
  "author":string,
  "description":string,
  "formatted":string,
  "likes":int,
  "link":string,
  "published":string,
  "tags":[string],
  "title":string
}
```

http://api.fssnip.net/1/snippet?all=true
Get

``` javascript
[{
    "author": string,
    "description": string,
    "likes": int,
    "link": string,
    "published": string,
    "title": string
}]
```

http://api.fssnip.net/1/snippet
Put

``` javascript
{ 
  "request": 
  { 
    "title": string, 
    "author": string, 
    "description": string, 
    "code": string, 
    "tags": [ string ], 
    "public": BOOL, 
    "link": string, 
    "nugetpkgs": [string], 
    "source": string 
   } 
}
```

**Comment by tpetricek** [comment]
Yes - although the PUT request should not have the wrapping `request` around it (that's used in the Fun3D code just to define multiple types in a single type provider call).

I added some code that adds a simple JSON API that's used to check for errors when inserting snippet. This uses JSON provider to generate the JSON values: https://github.com/tpetricek/FsSnip.Website/blob/master/code/pages/insert.fs#L70

If we had a lot of JSON APIs, it would probably be nicer to be able to just define a record and have that serialized using some library, but for this simple API, I think we can just use the same style as in the example above, i.e. use JSON provider with appropriate sample and then generate JSON using the provided type.

**Comment by treefrog00** [comment]
The new test site currently has "fssnip" as the subdomain (http://fssnip.azurewebsites.net/), whilst this feature requires Suave to route requests based on whether the subdomain is "api" or not. Any suggestions as to how to test this? Just make the routes at fssnip.azurewebsites.net/api for now and sort it out later?

I just tested deploying the app to Azure and it looks like the "host" header includes the full domain name for Azure websites, without any need for faffing proxy headers. There's also an identical "disguised-host" header, not sure what that's for.

**Comment by tpetricek** [comment]
Thanks for looking into this! Using just `fssnip.azurewebsites.net/api` sounds like a good plan to me. We can figure out how to do it on the subdomain once we have it implemented (it sounds like a fairly small change...)

**Comment by treefrog00** [comment]
The data returned by http://api.fssnip.net/1/snippet/11 is HTML not JSON, is that as intended?

**Comment by treefrog00** [comment]
also, should "all snippets" return the as-is contents of all public snippets as stored in memory, or should it be transformed to match the fields in the old version exactly? E.g. to change the "date" field to a "published" field of format "3 days ago", to remove the tags field, etc?

**Comment by tpetricek** [comment]
The data returned by `/1/snippet/11` probably has a wrong content type - but aside from that, it is JSON (most of the content is formatted snippet, which is HTML, but note that all the double quotes are encoded so that it is valid JSON).

As for the format changes - if we can keep the schema, that would be ideal. But I don't think we would break _many_ things by changing the reading of snippets. I suspect the only user of this is @timrobinson for FsNotebook....

**Comment by treefrog00** [comment]
As well as the content type the current API doesn't seem to escape the newlines, so it doesn't validate as JSON.

**Comment by tpetricek** [comment]
Ha, good catch. We should probably fix that. I guess that's a good sign that nobody is relying on it :)

**Comment by tpetricek** [comment]
(so feel free to change this so that it is just returning the internal representation - the only one that would be nice to keep is the insertion, because that's used by tryfsharp.org and by fun3d.net)

**Comment by treefrog00** [comment]
https://github.com/tpetricek/FsSnip.Website/pull/28

**Comment by tpetricek** [comment]
This is now done thanks to #29!

I just need to figure out how to configure Azure so that we can handle http://api.fssnipl.net requests...

**Comment by tpetricek** [comment]
It was quite easy to add the mapping for the api sub-domain in the end :) It's now deployed!
