### ISSUE TITLE
The resource you are looking for has been removed [WAS: Layout of snippets broken in Firefox]

### ISSUE THREAD

**Issue by treefrog00** [tpetricek/FsSnip.Website#26]
On my machine in Firefox, a snippet's code is squeezed into a tiny narrow column.

I can fix this by removing overflow:hidden on .snippet, though maybe that needs to be there for some other reason.

I was going to submit a PR, but whilst the website loads a css file called site.css I cannot find it in the github repo.

**Comment by tpetricek** [comment]
www.fssnip.net is still hosting an old version. Is this an issue in the new one? http://fssnip.azurewebsites.net/r6

**Comment by treefrog00** [comment]
Layout is not a problem in the new one, though clicking the tag http://fssnip.azurewebsites.net/tags/Ninety-Nine+F%23+Problems returns "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by treefrog00** [comment]
Same with clicking on an author's name

**Comment by tpetricek** [comment]
Thanks for reporting this :) It should all be working now. Magical config flag in `web.config` was needed!
