### ISSUE TITLE
Link to new site, or change domain registration?

### ISSUE THREAD

**Issue by treefrog00** [tpetricek/FsSnip.Website#27]
I regularly find snippets via google, but then get linked to the old site that is broken in Firefox. Is the new site still waiting on some feature before being marked ready? Or maybe a link on snippets on the old site could take you to the same thing on the new site?

**Comment by tpetricek** [comment]
Here is a list of critical issues/functionality that need to be added: https://github.com/tpetricek/FsSnip.Website/labels/status-priority

Once we have all of these, I definitely want to replace the old site with the new one! If you can help with one of these, that would be awesome!
