### ISSUE TITLE
FSharp.Formatting.svclog issue

### ISSUE THREAD

**Issue by forki** [tpetricek/FsSnip.Website#32]
- I cloned the project
- added the data folder
- opened in VS Code
- started integrated FAKE run from Code

![image](https://cloud.githubusercontent.com/assets/57396/11282870/e5ff0fa2-8f01-11e5-9429-00c145a33a91.png)

Any ideas what the FSharp.Formatting.svclog is doing. FAKE process can't access the file.

**Comment by tpetricek** [comment]
Repeatedly loading `FSharp.Formatting.fsx` (which is what the background loader does) causes this error, because F# Formatting locks the log file and never closes it.

We need a better solution - but for now, this is at least wrapped in `try .. catch` (https://github.com/tpetricek/FSharp.Formatting/blob/master/packages/FSharp.Formatting/FSharp.Formatting.fsx#L32) so the error is reported, but should not be breaking anything.

**Comment by forki** [comment]
ok so I'm ignoring it then.

btw: I noticed the watchers refreshes way to often. working on a fix

**Comment by forki** [comment]
argh it's too annoying. where is the source for FSharp.Formatting.fsx? we can catch that exn and jsut don't report it (or at least don't report the callstack and everything)

**Comment by tforkmann** [comment]
got the same error. had to reinstall paket and then it worked...

**Comment by tpetricek** [comment]
It's here: https://github.com/tpetricek/FSharp.Formatting/blob/master/packages/FSharp.Formatting/FSharp.Formatting.fsx#L56 

I wonder if we should just disable the log by default? I'm not particularly happy with having mysterious `svclog` files all over my machine anyway. We could have some environment variable like the R type provider that we can ask people to set when they report a bug... /cc @matthid

**Comment by tpetricek** [comment]
Not sure I'm allowed to vote twice, but +1 for environment variable.

The svclog file is also breaking the Azure deployment because it cannot be deleted...

**Comment by matthid** [comment]
I think we should keep on logging by default. An opt-out via environment variables is possible but I'm not sure it's actually needed as you can already access the trace-sources and configure them as needed.

Just iterate over all listeners of the two trace sources defined in https://github.com/tpetricek/FSharp.Formatting/blob/master/packages/FSharp.Formatting/FSharp.Formatting.fsx#L46 and _dispose_ (unlocks the files) them. After removing the listeners you can add whatever listener you need (console, eventlog, database, application insights, ... or any combination).

Let me know if this doesn't work for you

**Comment by matthid** [comment]
Just one addition: I don't really mind to have this as opt-in. So I don't have a strong opinion on this and certainly could iive with this being opt-in (I would just define the variable on all my builds). However it feels wrong to disable logging for such issues.

**Comment by tpetricek** [comment]
I'm not sure if there is any good way to solve the problem with the locked file... perhaps we could put it in `.logs` directory and use a unique name each time new file is created.

But sadly, in the two cases we're looking at here, we do not know when to call `Dispose`. The reload script for Suave simply calls `#load "app.fsx"` again (and it does not dispose of anything) and Azure does not kill the process when overwriting files (which seems weird, but that's what it must be doing). In both of these, nothing tells us that we should dispose of the loggers :-(. 

We could tweak the loader script, but I don't think we can do much about Azure. I think making logging opt-in would be sensible, though perhaps we can make it somehow on by default in ProjectScaffold?

**Comment by tpetricek** [comment]
Actually, another quite reasonable option for FsSnip would be just to not use the `fsx` load script from F# Formatting... that seems an obvious quick fix here.

**Comment by matthid** [comment]
We could go crazy and bundle two scripts: 
- One only loading the references (like before)
- One loading the first script and setting up logging

Then everybody can use whatever is needed :)
