### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by forki** [tpetricek/FsSnip.Website#43]
@tpetricek when are you going to deploy the latest version? seems the current live one is still asp.net MVC?

**Comment by tpetricek** [comment]
The current version of what's in the repo is automatically deployed to Azure: http://fssnip.azurewebsites.net/

I'll switch over to this version when we sort out the last few [high priority issues](https://github.com/tpetricek/FsSnip.Website/labels/status-priority).

(Then I'll also fetch the latest data from the old DB.)

**Comment by forki** [comment]
Thx.
