### ISSUE TITLE
google indexes update pages

### ISSUE THREAD

**Issue by vilinski** [tpetricek/FsSnip.Website#52]
google seems to index Update pages, where as a not owner you can't do anything

![fssnipupdate](https://cloud.githubusercontent.com/assets/259479/12387839/876f54e0-bdcf-11e5-9f63-889a8e032a58.PNG)

**Comment by tpetricek** [comment]
We definitely want to address this in the new version - what is the right way to do this? Add some sort of `robots.txt`?
