### ISSUE TITLE
Use Azure blob storage for snippet data

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#6]
Currently, the data is stored in local file system. This needs to be changed to use Azure blob storage instead (or even better, there should be some way to switch between local for development and Azure for testing & production).

**Comment by ilmaestro** [comment]
Does this include storing the index.json file as a blob? Or ideally would that metadata be stored in Azure tables?

**Comment by tpetricek** [comment]
We only modify the file very rarely (when a snippet is inserted) and so I think that keeping it in memory and saving it to a blob (when a new snippet is inserted) is perfectly sufficient. (That is, we can do pretty much the same thing as what the current code does - just replace local files with Azure blobs)

**Comment by ilmaestro** [comment]
Got it. And as far as being able to choose between Azure vs. Local
Filesystem, would that go in App.config? I'm still learning where to put
these types of things for Suave. I'll keep looking for best practices.

**Comment by tpetricek** [comment]
I'm actually not sure where to configure this.

We can perhaps start with a value at the top of `app.fsx` and once we have it, we can figure out what the best way of specifying this would be.

I would say that we can even keep it as simple as having two F# modules that have the same methods in them and then we just `open` the right one depending on whether we want to run the code locally or on Azure. (More complicated option would be to pass around an interface implementation - but we do not really need to choose the implementation at runtime, so perhaps having just two modules will do!)

**Comment by tpetricek** [comment]
Works now, closing, yay!
