### ISSUE TITLE
Google search engine optimization

### ISSUE THREAD

**Issue by Thorium** [tpetricek/FsSnip.Website#66]
Currently Google doesn't find fssnip.net snippets well.
I think this would be easy to improve:
- [x] Add the keywords to the meta-tag for the page header.
- [ ] Support optional tags in url: Instead of just: http://fssnip.net/sA/ add a variant that supports all the tags in the link: http://fssnip.net/sA/memoize-memoization-cache
- [ ] Change the url to contain these keywords in the links (in the main site listings, not in the link-part in the page itself), e.g: http://www.fssnip.net/tags/memoization

**Comment by tpetricek** [comment]
![55559913 1](https://cloud.githubusercontent.com/assets/485413/14285927/35112b8e-fb45-11e5-8dae-8644d494e704.jpg)

merged & deployed

**Comment by tpetricek** [comment]
Merged the first one!

Perhaps the default link could use cleaned-up version of the snippet title? e.g. http://fssnip.net/sA/concurrent-memoization?

**Comment by Thorium** [comment]
Now the 2 of 3 is done. After merge you can use: http://fssnip.net/c4/title/concurrent-memoization

Part 3 of 3 would be actually calling this in the tags page. There is now a helper function `generateCleanTitle`.
But the problem for part 3 is that currently the link to item is ID (int) and we don't want to make changes to the data schema. What is this format_id -function that is called in item.html:

``` html
<h3><a href="/{{ item.ID | format_id }}">{{ item.Title }}</a></h3>
```
