### ISSUE TITLE
search on site for "process" does not return RunProcess

### ISSUE THREAD

**Issue by jackfoxy** [tpetricek/FsSnip.Website#68]
enter process in search

http://fssnip.net/sw should be among the results

In general improved searching would benefit the community. Sadly I don't have time to work on this any time soon. Can this become an up-for-grabs issue?

**Comment by Rickasaurus** [comment]
For now you can use google as so: "site:fssnip.net process" but I agree better built in search would be very nice.

**Comment by tpetricek** [comment]
The search currently only looks at title & descriptions: https://github.com/fssnippets/fssnip-website/blob/master/code/pages/search.fs

Doing search over content wold require doing some indexing. Fun project for anyone interested in contributing :)

**Comment by Thorium** [comment]
Sorry wrong bug number in my commit; but this is actually case sensitivity issue, duplicate to #77 and fixed in my PR.

**Comment by Thorium** [comment]
Working now!

**Comment by jackfoxy** [comment]
@Thorium success! thanks
