### ISSUE TITLE
search does not work in Edge browser

### ISSUE THREAD

**Issue by jackfoxy** [tpetricek/FsSnip.Website#69]
Edge browser enter "process" hit enter

nothing...

**Comment by ahartman00** [comment]
edge version 25.1 here, its working for me

**Comment by jackfoxy** [comment]
It seems "process" is a remembered search by Edge, and it just does not execute. Entering any new search term works. I'm on 25.1 too.

Seems to be another annoyance with Edge and probably not an issue with the site. Closing.
