### ISSUE TITLE
Displaying multiple versions of a snippet

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FsSnip.Website#7]
The page currently displays only the latest version of a snippet. For some snippets, there are multiple versions of the same snippet. We should always display the latest one and we need to add buttons for navigating to the next/previous snippet.

(See also the functions `loadSnippet` and `loadRawSnippet`, which currently always load file named `0`, which stands for the first version.)

**Comment by darklajid** [comment]
Should be fixed with the merged PR

**Comment by tpetricek** [comment]
Indeed! Closed.
