### ISSUE TITLE
Type annotations are always visible.

### ISSUE THREAD

**Issue by Thorium** [tpetricek/FsSnip.Website#76]
Something has gone wrong.
Type annotations are always visible after the code.
Looks very messy.

**Comment by tpetricek** [comment]
Should be fixed now - you may need to do refresh in you.r browser.

We were getting `ERR_CONTENT_DECODING_FAILED` when accessing static file (http://fssnip.net/content/snippets.css), but restart solved it (cc @haf @ademar), but I don't have any more detailed report of what's going on.

**Comment by Thorium** [comment]
Working, thanks!

**Comment by haf** [comment]
My guess: while serving the static file a temporary file is written to disk. Are these names random and in that case, what is the collision rate? What about concurrent reads? What if the content is updated: is the new file correctly delineated if the content length e.g. has become smaller? Some ideas from the top of my head. I haven't had these errors myself.

**Comment by tpetricek** [comment]
I'll keep an eye on this and if it happens again, I'll investigate some more. Thanks @haf!
