### ISSUE TITLE
Load in tsunami.io fails

### ISSUE THREAD

**Issue by chrisjj** [tpetricek/FsSnip.Website#88]
On http://www.fssnip.net/q/title/Hello-world-F, click Load in tsunami.io

Gives

This site can’t be reached
tsunami.io’s server IP address could not be found.

**Comment by tpetricek** [comment]
I guess fssnip outlived both Tsunamin and TryFs. Can you send a pull request removing the two links?

**Comment by chrisjj** [comment]
And sadly the only alternative - tryfsharp - doesn't work on latest Chrome.

> Can you send a pull request removing the two links?

Sorry but that's beyond my ability :)
